src/java/com/lfantastico/domain/Event.java
package com.lfantastico.domain;

import java.math.BigDecimal;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class Event {
    private int id;
    private Date creation = new Date();
    private Date dateTime = new Date();
    private String location;
    private State state = State.SCHEDULED;
    private Orientation orientation = Orientation.HETERO;
    private AgeRange ageRange = new AgeRange(7, 77);
    private Relationship relationship;
    private Set<Keyword> keywords = new HashSet<Keyword>();
    private Language language;
    private Map<User,Attendance> attendances = new HashMap<User,Attendance>();
    private String address = "";
    private BigDecimal price = BigDecimal.valueOf(50);
    private int maxAttendees = 16;

    public enum State {
        SCHEDULED, PLACED, COMPLETED, CANCELED;

        public String getName() {
            return name();
        }
    }

    public enum Orientation {
        HETERO, GAY, LESBIAN;

        public String getName() {
            return name();
        }
    }

    public Event() {
    }

    public Event(Event other) {
        id = other.getId();
        dateTime = other.getDateTime();
        location = other.getLocation();
        state = other.getState();
        orientation = other.getOrientation();
        ageRange = other.getAgeRange();
        relationship = other.getRelationship();
        language = other.getLanguage();
        for (Map.Entry<User,Attendance> entry:
                other.getAttendances().entrySet()) {
            User user = entry.getKey();
            Attendance att = entry.getValue();
            attendances.put(user, new Attendance(user, this, att));
        }
        address = other.getAddress();
        price = other.getPrice();
        maxAttendees = other.getMaxAttendees();
    }

    public int getId() {
        return id;
    }

    public Date getCreation() {
        return creation;
    }

    public Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public Language getLanguage() {
        return language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public AgeRange getAgeRange() {
        return ageRange;
    }

    public void setAgeRange(AgeRange ageRange) {
        this.ageRange = ageRange;
    }

    public void setAgeRange(int min, int max) {
        setAgeRange(new AgeRange(min, max));
    }

    public Orientation getOrientation() {
        return orientation;
    }

    public void setOrientation(Orientation orientation) {
        this.orientation = orientation;
    }

    public Relationship getRelationship() {
        return relationship;
    }

    public void setRelationship(Relationship newValue) {
        this.relationship = newValue;
    }

    public boolean canAttend(User user) {
        switch (orientation) {
            case GAY:
                return user.getSex() == User.Sex.MALE;
            case LESBIAN:
                return user.getSex() == User.Sex.FEMALE;
        }
        return true;
    }

    public Map<User, Attendance> getAttendances() {
        return Collections.unmodifiableMap(attendances);
    }

    public void setAttendances(Map<User, Attendance> newValue) {
        attendances.clear();
        if (newValue != null) {
            attendances.putAll(newValue);
        }
    }

    public Attendance getAttendance(int number) {
        for (Attendance att: attendances.values()) {
            if (att.getNumber() == number) {
                return att;
            }
        }
        return null;
    }

    public User getUserAtPlace(int number) {
        for (Map.Entry<User,Attendance> entry: attendances.entrySet()) {
            User user = entry.getKey();
            Attendance att = entry.getValue();
            if (att.getNumber() == number) {
                return user;
            }
        }
        return null;
    }

    public Attendance getAttendance(User user) {
        return attendances.get(user);
    }

    public void addAttendance(User user, Attendance att) {
        attendances.put(user, att);
        att.setEvent(this);
        att.setUser(user);
    }

    public void removeAttendance(User user) {
        attendances.remove(user);
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Set<Keyword> getKeywords() {
        return Collections.unmodifiableSet(keywords);
    }

    public void setKeywords(Set<Keyword> newValue) {
        keywords.clear();
        if (newValue != null) {
            keywords.addAll(newValue);
        }
    }

    public int getMaxAttendees() {
        return maxAttendees;
    }

    public void setMaxAttendees(int maxAttendees) {
        if (maxAttendees != this.maxAttendees) {
            int oldcc = getCoupleCount();
            this.maxAttendees = maxAttendees;
            int newcc = getCoupleCount();
            for (Attendance att: attendances.values()) {
                int num = att.getNumber();
                if (num > oldcc && num <= newcc) {
                    att.setNumber(0);
                } else if (num > oldcc) {
                    num = num - oldcc + newcc;
                    if (num <= maxAttendees) {
                        att.setNumber(num);
                    } else {
                        att.setNumber(0);
                    }
                }
            }
        }
    }

    public int getCoupleCount() {
        return (maxAttendees+1)/2;
    }

    public boolean isPassed() {
        return dateTime.before(new Date());
    }

    public boolean getCanApply() {
        return state == State.SCHEDULED && !isPassed();
    }

    public boolean getCanEdit() {
        return state == State.SCHEDULED && !isPassed();
    }

    public boolean getCanPlace() {
        return state == State.SCHEDULED && !isPassed();
    }

    public boolean getCanCancel() {
        return state == State.SCHEDULED || state == State.PLACED;
    }
}

src/java/com/lfantastico/domain/Site.java
package com.lfantastico.domain;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class Site {
    private int id;
    private String hostName;
    private Map<String,SiteVersion> versions
            = new HashMap<String,SiteVersion>();
    private Set<Keyword> keywords = new HashSet<Keyword>();

    public String getHostName() {
        return hostName;
    }

    public void setHostName(String newValue) {
        hostName = newValue;
    }

    public Set<String> getSupportedLanguages() {
        return Collections.unmodifiableSet(versions.keySet());
    }

    public Map<String,SiteVersion> getVersions() {
        return Collections.unmodifiableMap(versions);
    }

    public void setVersions(Map<String,SiteVersion> newValue) {
        versions.clear();
        if (newValue != null) {
            versions.putAll(newValue);
        }
    }

    public boolean hasVersion(String language) {
        return versions.containsKey(language);
    }

    public SiteVersion getVersion(String language) {
        return versions.get(language);
    }

    public void setVersion(String language, SiteVersion version) {
        if (version == null) {
            versions.remove(language);
        } else {
            versions.put(language, version);
        }
    }

    public Set<Keyword> getKeywords() {
        return Collections.unmodifiableSet(keywords);
    }

    public void addKeyword(Keyword kw) {
        keywords.add(kw);
    }

    public void removeKeyword(Keyword kw) {
        keywords.remove(kw);
    }
}

src/java/com/lfantastico/domain/User.java
package com.lfantastico.domain;

import com.lfantastico.util.Util;
import java.math.BigDecimal;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Calendar;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TimeZone;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class User {
    private static final Logger LOG = LoggerFactory.getLogger(User.class);

    private int id = -1;
    private Status status;
    private String passwordHash;
    private String email;
    private String firstName;
    private String lastName;
    private String address1;
    private String address2;
    private String zip;
    private String city;
    private String state;
    private String country = "CH";
    private String phoneNumber;
    private String faxNumber;
    private Sex sex;
    private Orientation orientation = Orientation.HETERO;
    private Relationship relationship;
    private Date dateOfBirth;
    private Date registeredOn;
    private Language favoriteLanguage;
    private Set<Language> languages = new HashSet<Language>();
    private boolean admin;
    private String activationKey;
    private byte photo[];
    private BigDecimal credit = BigDecimal.ZERO;
    private String aboutMe;

    public enum Status {
        REGISTERED, ENABLED, DISABLED;

        public String getName() {
            return name();
        }
    }

    public enum Sex {
        MALE, FEMALE;

        public String getName() {
            return name();
        }

        public Sex getOpposite() {
            switch (this) {
                case FEMALE:
                    return MALE;
                default:
                    return FEMALE;
            }
        }
    }

    public enum Orientation {
        HETERO, HOMO, BI;

        public String getName() {
            return name();
        }
    }

    public User() {
    }

    public User(User other) {
        id = other.getId();
        status = other.getStatus();
        passwordHash = other.getPasswordHash();
        email = other.getEmail();
        firstName = other.getFirstName();
        lastName = other.getLastName();
        address1 = other.getAddress1();
        address2 = other.getAddress2();
        zip = other.getZip();
        city = other.getCity();
        state = other.getState();
        country = other.getCountry();
        phoneNumber = other.getPhoneNumber();
        faxNumber = other.getFaxNumber();
        sex = other.getSex();
        orientation = other.getOrientation();
        relationship = other.getRelationship();
        dateOfBirth = other.getDateOfBirth();
        registeredOn = other.getRegisteredOn();
        favoriteLanguage = other.getFavoriteLanguage();
        for (Language lng: other.getLanguages()) {
            languages.add(lng);
        }
        admin = other.isAdmin();
        activationKey = other.getActivationKey();
        photo = other.getPhoto();
        credit = other.getCredit();
        aboutMe = other.getAboutMe();
    }

    public int getId() {
        return id;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getFaxNumber() {
        return faxNumber;
    }

    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String newValue) {
        phoneNumber = newValue;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public Orientation getOrientation() {
        return orientation;
    }

    public void setOrientation(Orientation orientation) {
        this.orientation = orientation;
    }

    public Relationship getRelationship() {
        return relationship;
    }

    public void setRelationship(Relationship relationship) {
        this.relationship = relationship;
    }

    public void setPassword(String newValue) {
        passwordHash = Util.hash(newValue);
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public boolean hasPassword() {
        return passwordHash != null;
    }

    public boolean checkPassword(String password) {
        if (passwordHash == null) {
            throw new IllegalStateException("User password is not set");
        }
        if (password == null) {
            throw new IllegalArgumentException(
                "Null password passed to User.checkPassword");
        }
        String hash = Util.hash(password);
        return hash.equals(passwordHash);
    }

    public Date getRegisteredOn() {
        return registeredOn;
    }

    public void setRegisteredOn(Date registeredOn) {
        this.registeredOn = registeredOn;
    }

    public Sex getSex() {
        return sex;
    }

    public void setSex(Sex sex) {
        this.sex = sex;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status state) {
        this.status = state;
    }

    public Language getFavoriteLanguage() {
        return favoriteLanguage;
    }

    public void setFavoriteLanguage(Language language) {
        this.favoriteLanguage = language;
        if (language != null) {
            languages.add(language);
        }
    }

    public Set<Language> getLanguages() {
        return Collections.unmodifiableSet(languages);
    }

    public void setLanguages(Collection<Language> newLanguages) {
        languages.clear();
        if (newLanguages != null) {
            languages.addAll(newLanguages);
        }
        if (favoriteLanguage != null) {
            languages.add(favoriteLanguage);
        }
    }

    public boolean isAdmin() {
        return admin;
    }

    public void setAdmin(boolean admin) {
        this.admin = admin;
    }

    public String getActivationKey() {
        return activationKey;
    }

    public boolean getHasPhoto() {
        return photo != null;
    }

    public byte[] getPhoto() {
        return photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    public boolean activate(String key) {
        if (!key.equals(activationKey)) {
            return false;
        } else if (status == Status.REGISTERED) {
            status = Status.ENABLED;
        }
        return true;
    }

    public void generateActivationKey() {
        try {
            SecureRandom random = SecureRandom.getInstance("SHA1PRNG");
            byte data[] = new byte[8];
            random.nextBytes(data);
            activationKey = Util.hex(data);
        } catch (NoSuchAlgorithmException ex) {
            LOG.error("Error generating activation key", ex);
            throw new RuntimeException(ex.getMessage());
        }
    }

    public int getAgeOn(Date date) {
        Calendar cal = Calendar.getInstance(
                TimeZone.getTimeZone("Europe/Zurich"));
        cal.setTime(date);
        int year = cal.get(Calendar.YEAR);
        cal.setTime(dateOfBirth);
        int birthYear = cal.get(Calendar.YEAR);
        cal.set(Calendar.YEAR, year);
        Date birthDay = cal.getTime();
        int age = year-birthYear;
        if (date.before(birthDay)) {
            age -= 1;
        }
        return age;
    }

    public int getAgeNow() {
        return getAgeOn(new Date());
    }

    public BigDecimal getCredit() {
        return credit;
    }

    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    public void addCredit(BigDecimal amount) {
        credit = credit.add(amount);
    }

    public void subtractCredit(BigDecimal amount) {
        credit = credit.subtract(amount);
    }

    public String getAboutMe() {
        return aboutMe;
    }

    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }
}

web/WEB-INF/event-list.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<fmt:setLocale value="${session.locale}"/>
<c:set var="events" value="${page.queryEvents}"/>
<c:set var="dateMin" scope="request" value=""/>
<c:if test="${not empty page.dateMin}">
<fmt:formatDate var="dateMin" scope="request" type="date" pattern="dd/MM/yyyy" value="${page.dateMin}"/>
</c:if>
<c:set var="dateMax" scope="request" value=""/>
<c:if test="${not empty page.dateMax}">
<fmt:formatDate var="dateMax" scope="request" type="date" pattern="dd/MM/yyyy" value="${page.dateMax}"/>
</c:if>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><fmt:message key="event-list.title" bundle="${page.bundle}"/></title>
        <link rel='stylesheet' type='text/css' href='../css/stylesheet.css'>
        <c:import url="/WEB-INF/common/analytics.jsp"/>
    </head>
    <body id="${page.name}">
        <div id="wrapper">
            <h1><fmt:message key="event-list.title" bundle="${page.bundle}"/></h1>
            <div id="content">
                <c:import url="/WEB-INF/common/menu.jsp"/>
            <div id="search">
            <form method="POST" action="changeDates">
                <fmt:message key="event-list.from.label" bundle="${page.bundle}"/> <input name="dateMin" value="${dateMin}" maxlength="10" size="10" class="date">
                <fmt:message key="event-list.to.label" bundle="${page.bundle}"/> <input name="dateMax" value="${dateMax}" maxlength="10" size="10" class="date">
                <fmt:message var="label" key="event-list.search.label" bundle="${page.bundle}"/>
                <input type="submit" name="submit" value="<c:out value="${label}"/>">
            </form>
            <form method="POST" action="../event/create">
                <fmt:message var="label" key="event-list.new-event.label" bundle="${page.bundle}"/>
                <input type="submit" name="submit" value="<c:out value="${label}"/>">
            </form>
            </div>
<c:if test="${not empty events}">
        <table cellpadding="2" cellspacing="2" class="list">
            <thead>
                <tr>
                    <th><fmt:message key="event.date-time.label" bundle="${page.bundle}"/></th>
                    <th><fmt:message key="event.location.label" bundle="${page.bundle}"/></th>
                    <th><fmt:message key="event.language.label" bundle="${page.bundle}"/></th>
                    <th><fmt:message key="event.type.label" bundle="${page.bundle}"/></th>
                    <th><fmt:message key="event.age-range.label" bundle="${page.bundle}"/></>
                    <th><fmt:message key="event.address.label" bundle="${page.bundle}"/></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
    <c:forEach var="event" items="${events}">
                <tr>
                    <td><fmt:formatDate type="date" pattern="dd/MM/yyyy HH:mm" value="${event.dateTime}"/></td>
                    <td><c:out value="${event.location}"/></td>
                    <td><c:out value="${event.language.labels[session.language]}"/></td>
                    <td><c:out value="${helper.eventSummaries[event][session.language]}"/></td>
                    <td>${event.ageRange.minAge}&nbsp;-&nbsp;${event.ageRange.maxAge}</td>
                    <td>${event.address}</td>
                    <td><c:if test="${event.canEdit}">
                            <c:url var="url" value="/event/edit">
                                <c:param name="id" value="${event.id}"/>
                            </c:url>
                            <a href="${url}" class="button"><fmt:message key="event-list.edit.label" bundle="${page.bundle}"/></a>
                        </c:if>
                        <c:if test="${event.canPlace}">
                            <c:url var="url" value="/place/edit">
                                <c:param name="id" value="${event.id}"/>
                            </c:url>
                            <a href="${url}" class="button"><fmt:message key="event-list.place.label" bundle="${page.bundle}"/></a>
                        </c:if>
                        <c:if test="${event.canCancel}">
                            <c:url var="url" value="cancel">
                                <c:param name="id" value="${event.id}"/>
                            </c:url>
                            <a href="${url}" class="button"><fmt:message key="cancel.label" bundle="${page.bundle}"/></a>
                        </c:if></td>
                </tr>
    </c:forEach>
            </tbody>
        </table>
</c:if>
            </div>
            <c:import url="/WEB-INF/common/footer.jsp"/>
        </div>
        <c:import url="/WEB-INF/common/scripts.jsp"/>
    </body>
</html>

web/WEB-INF/place.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<fmt:setLocale value="${session.locale}"/>
<c:set var="date" scope="request" value=""/>
<c:set var="time" scope="request" value=""/>
<c:set var="event" scope="request" value="${page.event}"/>
<c:choose>
    <c:when test="${event.orientation.name == 'HETERO'}">
        <c:set var="keya" value="females"/>
        <c:set var="keyb" value="males"/>
        <c:set var="classa" value="fdroppable"/>
        <c:set var="classb" value="mdroppable"/>
    </c:when>
    <c:otherwise>
        <c:set var="keya" value="groupa"/>
        <c:set var="keyb" value="groupb"/>
        <c:set var="classa" value="droppable"/>
        <c:set var="classb" value="droppable"/>
    </c:otherwise>
</c:choose>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><fmt:message key="title" bundle="${page.bundle}"/></title>
        <link rel='stylesheet' type='text/css' href='../css/stylesheet.css'>
        <c:import url="/WEB-INF/common/analytics.jsp"/>
    </head>
    <body id="${page.name}">
        <div id="wrapper">
            <h1><fmt:message key="title" bundle="${page.bundle}"/></h1>
            <div id="content">
                <c:import url="/WEB-INF/common/menu.jsp"/>
                <table>
                    <col id="available">
                    <col id="groupa">
                    <col id="groupb">
                    <thead>
                        <tr>
                            <th><fmt:message key="available" bundle="${page.bundle}"/></th>
                            <th><fmt:message key="${keya}" bundle="${page.bundle}"/></th>
                            <th><fmt:message key="${keyb}" bundle="${page.bundle}"/></th>
                        </tr>
                    </thead>
                    <tbody>
                        <c:forEach var="r" begin="1" end="${event.coupleCount}">
                        <tr>
                            <c:if test="${r == 1}">
                            <td rowspan="${event.coupleCount}" id="av">
                                <c:forEach var="entry" items="${event.attendances}">
                                    <c:set var="user" value="${entry.key}"/>
                                    <c:set var="att" value="${entry.value}"/>
                                    <c:if test="${att.number == 0}">
                                        <c:set var="pclass" value="${user.sex.name == 'FEMALE' ? 'female' : 'male'}"/>
                                <span id="u${user.id}" class="${pclass}"><c:out value="${user.firstName} ${user.lastName}"/></span>
                                    </c:if>
                                </c:forEach>
                            </td>
                            </c:if>
                            <c:set var="user" value="${helper.userAtPlace[event][r]}"/>
                            <c:choose>
                                <c:when test="${empty user}">
                                    <td class="groupa ${classa}" id="p${r}">&nbsp;</td>
                                </c:when>
                                <c:otherwise>
                                    <c:set var="pclass" value="${user.sex.name == 'FEMALE' ? 'female' : 'male'}"/>
                                    <td class="groupa ${classa}" id="p${r}"><span id="u${user.id}" class="${pclass}"><c:out value="${user.firstName} ${user.lastName}"/></span></td>
                                </c:otherwise>
                            </c:choose>
                            <c:set var="user" value="${helper.userAtPlace[event][r+event.coupleCount]}"/>
                            <c:choose>
                                <c:when test="${empty user}">
                                    <td class="groupb ${classb}" id="p${r+event.coupleCount}">&nbsp;</td>
                                </c:when>
                                <c:otherwise>
                                    <c:set var="pclass" value="${user.sex.name == 'FEMALE' ? 'female' : 'male'}"/>
                                    <td class="groupb ${classb}" id="p${r+event.coupleCount}"><span id="u${user.id}" class="${pclass}"><c:out value="${user.firstName} ${user.lastName}"/></span></td>
                                </c:otherwise>
                            </c:choose>
                        </tr>
                        </c:forEach>
                        <tr></tr>
                    </tbody>
                </table>
                <div><form method="POST" action="validate">
                    <fmt:message var="label" key="validate.label" bundle="${page.bundle}"/>
                    <input type="submit" name="submit" value="${label}">
                </form></div>
            </div>
            <c:import url="/WEB-INF/common/footer.jsp"/>
        </div>
        <script type="text/javascript" src="../js/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="../js/jquery-ui-1.8.4.custom.min.js"></script>
        <script type="text/javascript">
            $(function() {
                function move(elm, to) {
                    var id = elm.attr("id");
                    var n = $("<span/>").appendTo(to);
                    if (elm.hasClass("female")) {
                        n.addClass("female");
                    } else if (elm.hasClass("male")) {
                        n.addClass("male");
                    }
                    n.text(elm.text());
                    elm.remove();
                    n.attr("id", id);
                    n.draggable({ revert: 'invalid' });
                }

                function placeIt(event, ui) {
                    var that = this;
                    var drag = ui.draggable;
                    $.ajax({
                        type: "POST",
                        url: "place",
                        data: "user=" + drag.attr("id") +
                                "&place=" + $(that).attr("id"),
                        dataType: "text",
                        success: function(data) {
                            var parent = drag.parent();
                            var cur = $("span", that);
                            if (cur.length) {
                                move(cur, $("#av"));
                            }
                            $(that).empty();
                            move(drag, that);
                            if (parent.attr("id") !== "av") {
                                parent.text("\u00A0"); // &nbsp;
                            }
                        }
                    });
                }

                function removeIt(event, ui) {
                    var that = this;
                    var drag = ui.draggable;
                    $.ajax({
                        type: "POST",
                        url: "remove",
                        data: "user=" + drag.attr("id"),
                        dataType: "text",
                        success: function(data) {
                            var parent = drag.parent();
                            move(drag, that);
                            parent.text("\u00A0"); // &nbsp;
                        }
                    });
                }

                $(".female").draggable({ revert: 'invalid' });
                $(".male").draggable({ revert: 'invalid' });
                $("#av").droppable({
                    accept: function(drag) {
                        if ($(drag).parent().attr("id") === $(this).attr("id")) {
                            return false;
                        }
                        return true;
                    },
                    drop: removeIt
                })
                $(".droppable").droppable({
                    accept: function(drag) {
                        if ($(drag).parent().attr("id") === $(this).attr("id")) {
                            return false;
                        }
                        return true;
                    },
                    drop: placeIt
                });
                $(".fdroppable").droppable({
                    accept: function(drag) {
                        if ($(drag).parent().attr("id") === $(this).attr("id")) {
                            return false;
                        }
                        return $(drag).hasClass("female");
                    },
                    drop: placeIt
                });
                $(".mdroppable").droppable({
                    accept: function(drag) {
                        if ($(drag).parent().attr("id") === $(this).attr("id")) {
                            return false;
                        }
                        return $(drag).hasClass("male");
                    },
                    drop: placeIt
                });
            });
        </script>
    </body>
</html>