src/java/com/lfantastico/domain/Language.java
package com.lfantastico.domain;

import java.util.HashMap;
import java.util.Map;

public class Language {
    private String code;
    private Map<String,String> labels = new HashMap<String,String>();

    /**
     * @deprecated should not be called directly. It's only use is via
     * serialization or hibernate.
     */
    @Deprecated()
    public Language() {
    }

    public Language(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public String getLabel(String language) {
        return labels.get(language);
    }

    public void setLabel(String language, String value) {
        labels.put(language, value);
    }

    public Map<String,String> getLabels() {
        return new HashMap<String,String>(labels);
    }

    public void setLabels(Map<String,String> newValue) {
        labels.clear();
        if (newValue != null) {
            labels.putAll(newValue);
        }
    }

    public String getNativeLabel() {
        return labels.get(code);
    }

    public String getDefaultLabel() {
        String result = getNativeLabel();
        if (result == null && !labels.isEmpty()) {
            result = labels.get("en");
            if (result == null) {
                result = labels.get("fr");
                if (result == null) {
                    result = labels.values().iterator().next();
                }
            }
        }
        return result;
    }
}

src/java/com/lfantastico/domain/Site.java
package com.lfantastico.domain;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class Site {
    private int id;
    private String hostName;
    private Map<String,SiteVersion> versions
            = new HashMap<String,SiteVersion>();
    private Set<Keyword> keywords = new HashSet<Keyword>();

    public String getHostName() {
        return hostName;
    }

    public void setHostName(String newValue) {
        hostName = newValue;
    }

    public Set<String> getSupportedLanguages() {
        return Collections.unmodifiableSet(versions.keySet());
    }

    public Map<String,SiteVersion> getVersions() {
        return Collections.unmodifiableMap(versions);
    }

    public void setVersions(Map<String,SiteVersion> newValue) {
        versions.clear();
        if (newValue != null) {
            versions.putAll(newValue);
        }
    }

    public boolean hasVersion(String language) {
        return versions.containsKey(language);
    }

    public SiteVersion getVersion(String language) {
        return versions.get(language);
    }

    public void setVersion(String language, SiteVersion version) {
        if (version == null) {
            versions.remove(language);
        } else {
            versions.put(language, version);
        }
    }

    public Set<Keyword> getKeywords() {
        return Collections.unmodifiableSet(keywords);
    }

    public void addKeyword(Keyword kw) {
        keywords.add(kw);
    }

    public void removeKeyword(Keyword kw) {
        keywords.remove(kw);
    }
}

web/WEB-INF/common/analytics.jsp
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-8217645-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

web/WEB-INF/common/footer.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<jsp:useBean id="now" class="java.util.Date"/>
<div id="footer">
    <div id="copyright">
        &copy;2010-<fmt:formatDate value="${now}" pattern="yyyy"/> &ndash; L. Fantastico &ndash; Soir&eacute;e Speed Dating &ndash; Gen&egrave;ve &ndash; Lausanne
    </div>
    <div id="credit">
        <a href="http://www.studiostrob.ch" title="Besoin d'un site? Contactez-nous pour une offre gratuite et sans engagement" target="_blank">Webdesign Studiostrob Gen&egrave;ve</a>
    </div>
    <div class="clear"></div>
</div>

web/WEB-INF/common/inplace.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<c:if test="${session.editMode}">
<div class="dialog" id="textedit" title="Edit text">
    <form action="setPageText" method="post">
        <input id="text-key" type="hidden" name="key" value=""/>
        <div><textarea id="text-value" name="text" cols="80" rows="12"></textarea></div>
        <div><input type="submit" name="submit" value="OK"></div>
    </form>
</div>
<script type="text/javascript">
    $(function() {
        $("#text-value").ckeditor({
            toolbar: [
                ['Source'],
                ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print', 'SpellChecker', 'Scayt'],
                ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
                ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
                ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
                ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
                ['Link','Unlink','Anchor'],
                ['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],
                ['Format'],
                ['Maximize', 'ShowBlocks','-','About']
            ],
            skin: 'v2',
            filebrowserImageBrowseUrl : '../browser/browse',
            filebrowserImageUploadUrl : '../browser/upload',
/*            contentsCss: '../css/stylesheet.css', */
            language: '${session.language}',
            contentsLanguage: '${session.language}',
            scayt_sLang: '${session.language}_CH',
            ignoreEmptyParagraph: true,
            fullPage: false,
            resize_enabled: false
        });
        $(".editable>a").click(function() {
            var href = $(this).attr("href");
            var re = /(editPageText|editSiteText)[?]key=([A-Za-z0-9_\-.]+)/;
            var res = re.exec(href);
            if (!res) {
                return true;
            }
            if (res[1] === "editPageText") {
                $("#textedit form").attr("action", "setPageText");
            } else {
                $("#textedit form").attr("action", "setSiteText");
            }
            $("#text-key").val(res[2]);
            $("#text-value").val($(this).parent().children("div").html());
            $("#textedit").dialog({
                width: 640,
                modal: false,
                close: function() {
                    $("#textedit").dialog("destroy");
                }
            });
            return false;
        });
    });
</script>
</c:if>

web/WEB-INF/common/menu.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<ul id="nav">
    <li id="item-main"><a href="../main/start"><fmt:message key="menu.home" bundle="${page.bundle}"/></a></li>
    <li id="item-info"><a href="../info/"><fmt:message key="menu.help" bundle="${page.bundle}"/></a></li>
    <li id="item-faq"><a href="../faq/"><fmt:message key="menu.faq" bundle="${page.bundle}"/></a></li>
    <li id="item-contact"><a href="../contact/"><fmt:message key="menu.contact" bundle="${page.bundle}"/></a></li>
</ul>
<ul id="user">
<c:choose>
    <c:when test="${empty helper.user}">
    <li><a href="../main/login"><fmt:message key="menu.login" bundle="${page.bundle}" /></a></li>
    </c:when>
    <c:otherwise>
    <li><a href="../profile/myProfile"><c:out value="${helper.user.firstName} ${helper.user.lastName}"/></a></li>
    </c:otherwise>
</c:choose>
</ul>
<ul id="lang-mnu">
<c:forEach var="lc" items="${helper.site.supportedLanguages}">
<c:set var="lng" value="${helper.languages[lc]}"/>
<c:url var="url" value="setLanguage">
    <c:param name="language" value="${lng.code}"/>
</c:url>
<c:choose>
    <c:when test="${lng.code==page.language}">
    </c:when>
    <c:otherwise>
    <li><a href="${url}"><c:out value="${lng.defaultLabel}"/></a></li>
    </c:otherwise>
</c:choose>
</c:forEach>
</ul>
<c:if test="${request.roles['admin']}">
<ul id="admin-menu">
    <li id="item-user-list"><a href="../user-list/"><fmt:message key="menu.users" bundle="${page.bundle}"/></a></li>
    <li id="item-event-list"><a href="../event-list/"><fmt:message key="menu.events" bundle="${page.bundle}"/></a></li>
    <li id="item-emails"><a href="../email/"><fmt:message key="menu.emails" bundle="${page.bundle}"/></a></li>
    <li id="mode-sel">
    <c:choose>
        <c:when test="${session.editMode}">
            <a href="setEditMode?on=false"><fmt:message key="menu.normal-mode" bundle="${page.bundle}"/></a>
        </c:when>
        <c:otherwise>
            <a href="setEditMode?on=true"><fmt:message key="menu.edit-mode" bundle="${page.bundle}"/></a>
        </c:otherwise>
    </c:choose>
    </li>
</ul>
</c:if>
<div class="clear"></div>

web/WEB-INF/common/profile-dialog.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<fmt:setLocale value="${session.locale}"/>
<c:set var="user" value="${page.user}"/>
<c:set var="relationship" value="any"/>
<c:if test="${not empty user.relationship}">
    <c:set var="relationship" value="${user.relationship.name}"/>
</c:if>
<fmt:formatDate var="dateOfBirth" scope="request" type="date" pattern="dd/MM/yyyy" value="${user.dateOfBirth}"/>
<c:set var="language" value=""/>
<c:if test="${not empty user.favoriteLanguage}">
    <c:set var="language" value="user.favoriteLanguage.code"/>
</c:if>
<div id="profile-dlg" class="dialog">
    <h1><fmt:message key="title" bundle="${page.bundle}">
            <fmt:param value="${user.firstName} ${user.lastName}"/>
        </fmt:message></h1>
    <c:url var="url" value="/photo">
        <c:param name="user" value="${user.email}"/>
    </c:url>
    <fmt:message var="alt" key="photo.label" bundle="${page.bundle}"/>
    <div id="photo"><img alt="${alt}" src="${url}"></div>
    <table border="0" cellpadding="2" cellspacing="2">
        <tbody>
            <tr>
                <td><fmt:message key="email.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${user.email}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="sex.label" bundle="${page.bundle}"/>: </td>
                <td><fmt:message key="sex.${user.sex.name}" bundle="${page.bundle}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="orientation.label" bundle="${page.bundle}"/>: </td>
                <td><fmt:message key="orientation.${user.orientation.name}" bundle="${page.bundle}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="relationship.label" bundle="${page.bundle}"/>: </td>
                <td><fmt:message key="relationship.${relationship}" bundle="${page.bundle}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="language.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${helper.languages[language].labels[session.language]}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="dateOfBirth.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${dateOfBirth}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="lastName.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${user.lastName}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="firstName.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${user.firstName}"/>"></td>
            </tr>
            <tr>
                <td><fmt:message key="address.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${user.address1}"/></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><c:out value="${user.address2}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="zip.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${user.zip}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="city.label" bundle="${page.bundle}"/> </td>
                <td><c:out value="${user.city}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="country.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${helper.countries[user.country].labels[session.language]}"/></td>
            </tr>
            <tr>
                <td><fmt:message key="state.label" bundle="${page.bundle}"/>: </td>
                <td><c:choose>
                        <c:when test="${user.country=='US'}"><c:out value="${helper.states[user.state].name}"/></c:when>
                        <c:otherwise>-</c:otherwise>
                    </c:choose></td>
            </tr>
            <tr>
                <td><fmt:message key="phone.label" bundle="${page.bundle}"/>: </td>
                <td><c:out value="${user.phoneNumber}"/></td>
            </tr>
<c:if test="${request.roles['admin']}">
            <tr>
                <td><fmt:message key="admin.label" bundle="${page.bundle}"/>: </td>
                <td><c:choose>
                        <c:when test="${user.admin}">oui</c:when>
                        <c:otherwise>non</c:otherwise>
                    </c:choose></td>
            </tr>
            <tr>
                <td><fmt:message key="credit.label" bundle="${page.bundle}"/>: </td>
                <fmt:formatNumber var="credit" value="${user.credit}" pattern="0.00"/>
                <td><c:out value="${credit}"/></td>
            </tr>
</c:if>
        </tbody>
    </table>
</div>
<c:import url="/WEB-INF/common/scripts.jsp"/>
<script type="text/javascript">
    function showProfileDialog(userid) {
        $("#profile-dlg").dialog({
            width: 640,
            modal: true,
            close: function() {
                $("#profile-dlg").dialog("destroy");
            }
        });
    }
</script>

web/WEB-INF/common/scripts.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<script type="text/javascript" src="../js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="../js/jquery-ui-1.8.4.custom.min.js"></script>
<script type="text/javascript" src="../ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="../ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">
    var monthNames = {
        en: ['January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December'],
        fr: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin',
                'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Decembre']
    };
    var monthShortNames = {
        en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        fr: ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jun',
                'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Dec']
    };
    $(function() {
        $(".date").datepicker({
            dateFormat: "dd/mm/yy",
            showAnim: 'slideDown',
            monthNames: monthNames.${session.language},
            monthShortNames: monthShortNames.${session.language}
        });
    });
</script>